version: 2.1

jobs:
  build:
    machine:
      image: "ubuntu-2204:2023.07.2"
    environment:

      # Set this to the upstream version tag to use/build
      UPSTREAM_TAG: v1.9.3

    steps:
      - checkout

      - run:
          name: Install dependencies for unbound
          command: |
            sudo apt-get update 
            sudo apt-get install -y libunbound-dev make

      - run:
          name: Clone upstream repository
          command:
            git clone -b $UPSTREAM_TAG --depth 1 https://github.com/coredns/coredns.git

      - run:
          name: Build Docker image
          command: |
            cd coredns
            echo "unbound:github.com/coredns/unbound" >> plugin.cfg
            sed -i 's/CGO_ENABLED?=0/CGO_ENABLED?=1/g' Makefile
            go get github.com/coredns/unbound
            go generate
            make

            sed -i 's/FROM scratch/FROM debian:stable-slim/g' Dockerfile
            docker buildx build . -t quay.io/giantswarm/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1-unbound
            ls -la

      - run:
          name: Docker login
          command: |
            echo -n "${QUAY_PASSWORD}" | docker login --username "${QUAY_USERNAME}" --password-stdin quay.io

      - run:
          name: Docker push (SHA1 tag)
          command: |
            docker push quay.io/giantswarm/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1-unbound

      - run:
          name: Docker push release (only for a tagged release)
          command: |
            if [ ! -z "${CIRCLE_TAG}" ] && [ -z "${CIRCLE_BRANCH}" ]
            then
                docker push quay.io/giantswarm/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG-unbound

                # China
                echo -n "${ALIYUN_PASSWORD}" | docker login --username "${ALIYUN_USERNAME}" --password-stdin giantswarm-registry.cn-shanghai.cr.aliyuncs.com
                docker tag  quay.io/giantswarm/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG-unbound giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG-unbound
                docker push giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG-unbound
            else
                echo "Not pushing release tag"
            fi

workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
